version: "3.4"
services:
  db:
    image: 'mysql:5.7'
    env_file:
      - .env
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: '${DATABASE_PASSWORD}'
      MYSQL_DATABASE: '${DATABASE_NAME}'
    expose:
      - 3306
    volumes:
      - './.docker/data/db:/var/lib/mysql'
      - './.docker/mnt:/mnt'

  app:
    build:
      context: .
    volumes:
      - './:/var/www/html'
      - './.docker/vendor:/var/www/html/vendor'
      - './docker-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'
    user: app:www-data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
    links:
      - db

  web:
    image: 'nginx:alpine'
    ports:
      - '8001:80'
    volumes:
      - './:/var/www/html'
      - './.docker/vendor:/var/www/html/vendor'
      - './conf.nginx:/etc/nginx/conf.d/default.conf'
    depends_on:
      - app
      - db
    links:
      - app
